# Generated by Django 6.0 on 2026-01-05 03:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del medicamento')),
                ('dose', models.CharField(max_length=100, verbose_name='Dosis')),
                ('route', models.CharField(choices=[('VO', 'Vía Oral'), ('IV', 'Intravenoso'), ('IM', 'Intramuscular'), ('SC', 'Subcutáneo'), ('TOP', 'Tópico')], default='VO', max_length=10, verbose_name='Vía')),
                ('freq', models.CharField(max_length=100, verbose_name='Frecuencia')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('due', 'Pendiente'), ('given', 'Administrado')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicación',
                'verbose_name_plural': 'Medicaciones',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=20, verbose_name='Género')),
                ('cc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula de ciudadanía')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('eps', models.CharField(max_length=100, verbose_name='EPS')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('diagnosticos', models.TextField(blank=True, null=True, verbose_name='Diagnósticos')),
                ('status', models.CharField(choices=[('Estable', 'Estable'), ('En observación', 'En observación'), ('Alta', 'Alta')], default='Estable', max_length=20, verbose_name='Estado')),
                ('enfermedades_previas', models.TextField(blank=True, null=True, verbose_name='Enfermedades previas')),
                ('cirugias', models.TextField(blank=True, null=True, verbose_name='Cirugías previas')),
                ('nombre_acudiente', models.CharField(max_length=200, verbose_name='Nombre del acudiente')),
                ('telefono_acudiente', models.CharField(max_length=20, verbose_name='Teléfono del acudiente')),
                ('room', models.CharField(blank=True, max_length=10, null=True, verbose_name='Habitación')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('administered_by', models.CharField(max_length=200, verbose_name='Administrado por')),
                ('notes', models.TextField(blank=True, null=True)),
                ('administered_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meds_given', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ClinicalH.medication')),
            ],
            options={
                'verbose_name': 'Historial de Medicación',
                'verbose_name_plural': 'Historiales de Medicación',
                'ordering': ['-administered_at'],
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='ClinicalH.patient'),
        ),
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('LAB', 'Laboratorio'), ('VITALS', 'Signos Vitales'), ('MED', 'Medicación'), ('PROCEDURE', 'Procedimiento'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('doctor_name', models.CharField(max_length=200, verbose_name='Por:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por (Usuario)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_notes', to='ClinicalH.patient')),
            ],
            options={
                'verbose_name': 'Nota Médica',
                'verbose_name_plural': 'Notas Médicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
