# Generated by Django 6.0 on 2026-01-19 00:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicalH', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de edición')),
                ('previous_content', models.TextField(verbose_name='Contenido anterior')),
                ('new_content', models.TextField(verbose_name='Contenido nuevo')),
                ('previous_title', models.CharField(max_length=200, verbose_name='Título anterior')),
                ('new_title', models.CharField(max_length=200, verbose_name='Título nuevo')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='ClinicalH.medicalnote')),
            ],
            options={
                'verbose_name': 'Historial de Edición de Nota',
                'verbose_name_plural': 'Historiales de Edición de Notas',
                'ordering': ['-edited_at'],
            },
        ),
    ]
